# Generated by Django 3.2.7 on 2021-10-02 16:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
